### ISSUE TITLE
lttv/lttv/module.c:202: undefined reference to `g_module_error'

### ISSUE THREAD

**Issue by nickma82** [giraldeau/lttv#1]
Hi,
after installing all the dependencies I had to add `-lgmodule-2.0` in the [lttv/lttv/Makefile.am](https://github.com/giraldeau/lttv/blob/cpu-usage/lttv/lttv/Makefile.am#L4) to the LDADD.

Otherwise I received linker errors against all kinds of `g_module_*' methods.
Best

**Comment by giraldeau** [comment]
Thanks for this report, however lttv is deprecated for many years now. For kernel tracing, I recommend TraceCompass.
